###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "rajesh",
    "email": "rajesh@gmail.com",
    "password":"rajesh",
    "role": "admin"

}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "rajesh@gmail.com",
    "password":"rajesh"
}

###
POST http://localhost:3000/api/products/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmM5NzVlZTFmOGE4OWRkYjdkOGVkNyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTk0NzEwOH0.Rv9o_G_PsjPdE4EOcDeN245xFf3tVbbXuTxHI279u6k
Content-Type: application/json
{ "name": "DANVOUY Womens T Shirt Casual Cotton Short", "category": "women's clothing", "price": 12.99, "stock": 145 }


 

###
//user details
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "ranjith",
    "email": "ranjith@gmail.com",
    "password":"ranjith",
    "role": "customer"
}

###
POST http://localhost:3000/api/auth/login 
Content-Type: application/json

{
    "email": "ranjith@gmail.com",
    "password":"ranjith"
}

###
//add to cart
POST http://localhost:3000/api/cart/add 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmM5ZjYxZDJhNThmM2E1NjdiNGMyNSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1MTk0OTE5MH0.5RMS031PNG2mjkeyRXnhdRPi6T9ZwqpuQp0i92ULiKk
Content-Type: application/json

{
    "productId": "686c99d8e1f8a89ddb7d8ee2",
    "quantity": 3
}

###
//get cart details
GET http://localhost:3000/api/cart/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmM5ZjYxZDJhNThmM2E1NjdiNGMyNSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1MTk0OTE5MH0.5RMS031PNG2mjkeyRXnhdRPi6T9ZwqpuQp0i92ULiKk

###
//update cart
PUT http://localhost:3000/api/cart/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NmM5ZjYxZDJhNThmM2E1NjdiNGMyNSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1MTk0OTE5MH0.5RMS031PNG2mjkeyRXnhdRPi6T9ZwqpuQp0i92ULiKk
Content-Type: application/json

{
    "productId": "686c99d8e1f8a89ddb7d8ee2",
    "quantity": 3
}
  